
# This is a basic workflow to help you get started with Actions

name: entities:0.0

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string : 
#    weekly #m h d/m m d/w 
    - cron:  '20 5 * * 1'
#    daily #m h d/m m d/w 
#    - cron:  '30 1 * * *'
   
jobs:
  docker-run-action:
    runs-on: ubuntu-latest
    container:
      image: credocker/crepython:2020.0
      volumes:
        - ${{ github.workspace }}:/cre/python
    steps:
      - uses: actions/checkout@v3
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
#        with:
#          ref: main
      - name: cd /cre/python/
        run: (cd /cre/python/)
      - name: Install spacy textblob
        run: (pip3 install spacy==2.2.4 textblob==0.15.3 nltk==3.8)
      - name: Install download en_core_web_md
        run: (python3 -m spacy download en_core_web_md)
      - name: Run entities
        run: (python3 entities.py)
      - name: Submit changes       
        uses: EndBug/add-and-commit@v9
        with:
#          pull: '--rebase --autostash ...'
          add: 'csv/sentiments_*.csv'
          tag_push: '--force'
